### ISSUE TITLE
Generierung von Inserttags innerhalb von <a>

### ISSUE THREAD

**Issue by wangaz** [Toflar/contao-css-class-replacer#7]
Über TinyMCE eingefügte Verlinkungen zu internen Seiten funktionieren nicht korrekt:
    <a href="{{link_url::2}}">Link</a>
wird bei aktiviertem *css-class-replacer* im FE zu
    <a href="%7B%7Blink_url::2%7D%7D">Link</a>

Außerhalb des Tags funktioniert das einwandfrei.

Contao: 3.4.0

**Comment by Toflar** [comment]
Hmm, das sollte eigentlich mit https://github.com/netzmacht/php-dom-manipulator/commit/121462c8b2d9b72574cc96b6172a66bb3d1a130c behoben sein. Wichtig ist, dass du Version 2.0 des Moduls verwendest. Die verwendet nämlich neu die Bibliothek von David und sollte es immer noch tun, wäre das Ticket folglich hier richtig: https://github.com/netzmacht/php-dom-manipulator
Ich schliesse es deshalb. /cc @dmolineus
